import { mechanismComponentDefinition } from "./mechanism-component-definitions.js";
import { COMPONENT_GEOMETRY_DEFINITIONS } from "./component-geometry-definitions.js";
import { issueInertPlainData } from "./plain-data-contract.js";

const port = (id, kind, behavior, direction, multiplicity, metadata = {}) =>
  Object.freeze({
    id,
    kind,
    behavior,
    direction,
    multiplicity,
    ...metadata,
  });

const TYPE_DEFINITIONS = {
  beam: {
    name: "Alloy Beam",
    cat: "structure",
    icon: "▬",
    mass: 18,
    color: 0x91a7b1,
    desc: "Rigid structural member",
    size: [2.4, 0.35, 0.35],
    ports: [
      port("A", "mechanical", "fixed", "bidirectional", "one"),
      port("B", "mechanical", "fixed", "bidirectional", "one"),
      port(
        "SURFACE",
        "mechanical",
        "structural-surface",
        "bidirectional",
        "many",
      ),
    ],
  },
  plate: {
    name: "Mounting Plate",
    cat: "structure",
    icon: "▰",
    mass: 22,
    color: 0x667982,
    desc: "Stable component base",
    size: [2.4, 0.18, 2.4],
    ports: [
      port("TOP", "mechanical", "structural-surface", "bidirectional", "many"),
      port(
        "BOTTOM",
        "mechanical",
        "structural-surface",
        "bidirectional",
        "many",
      ),
    ],
  },
  cargo: {
    name: "Mission Payload",
    cat: "structure",
    icon: "▣",
    mass: 80,
    color: 0xd19a43,
    desc: "Instrumented 80 kg challenge cargo",
    size: [1.2, 0.9, 1.1],
    ports: [
      port("MOUNT A", "mechanical", "fixed", "bidirectional", "one"),
      port("MOUNT B", "mechanical", "fixed", "bidirectional", "one"),
      port("MOUNT C", "mechanical", "fixed", "bidirectional", "one"),
      port("MOUNT D", "mechanical", "fixed", "bidirectional", "one"),
    ],
    payload: true,
  },
  nosecone: {
    name: "Aero Nose Cone",
    cat: "structure",
    icon: "△",
    mass: 18,
    color: 0xd6dfe0,
    desc: "Low-drag thermal leading surface",
    size: [0.9, 1.35, 0.9],
    ports: [port("BASE", "mechanical", "fixed", "bidirectional", "one")],
    noseRadius: 0.09,
    heatLimit: 1450,
  },
  heatshield: {
    name: "Ablative Heat Shield",
    cat: "structure",
    icon: "◒",
    mass: 32,
    color: 0x4f4540,
    desc: "Sacrificial phenolic-carbon thermal protection",
    size: [1.15, 0.3, 1.15],
    ports: [port("BACK", "mechanical", "fixed", "bidirectional", "one")],
    pyrolysisTemperatureK: 560,
    heatOfAblationJkg: 22000000,
  },
  fin: {
    name: "Stabilizing Fin",
    cat: "structure",
    icon: "◢",
    mass: 6,
    color: 0xaab8ba,
    desc: "Aerodynamic restoring surface",
    size: [0.12, 1.05, 0.72],
    ports: [port("ROOT", "mechanical", "fixed", "bidirectional", "one")],
    liftSlope: 2.8,
  },
  axle: {
    name: "Steel Axle",
    cat: "motion",
    icon: "━",
    color: 0xabb8bc,
    desc: "Transfers rotation",
    ports: [
      port("LEFT", "mechanical", "rotary-coupling", "bidirectional", "one"),
      port("RIGHT", "mechanical", "rotary-coupling", "bidirectional", "one"),
      port("JOURNAL", "mechanical", "rotary-coupling", "bidirectional", "many"),
      port(
        "JOURNAL LEFT",
        "mechanical",
        "rotary-coupling",
        "bidirectional",
        "one",
      ),
      port(
        "JOURNAL RIGHT",
        "mechanical",
        "rotary-coupling",
        "bidirectional",
        "one",
      ),
    ],
    mechanism: mechanismComponentDefinition("axle"),
  },
  bearing: {
    name: "Pillow Block Bearing",
    cat: "motion",
    icon: "⊙",
    color: 0x718b91,
    desc: "Supports a rotating shaft while carrying radial load",
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("SHAFT", "mechanical", "revolute-support", "bidirectional", "one"),
    ],
    mechanism: mechanismComponentDefinition("bearing"),
  },
  gear12: {
    name: "12T Pinion Gear",
    cat: "motion",
    icon: "⚙",
    mass: 6,
    color: 0xd9a441,
    desc: "Fast, low-torque gear",
    teeth: 12,
    radius: 0.41,
    ports: [
      port("AXLE", "mechanical", "rotary-coupling", "bidirectional", "one"),
      port("MESH", "mesh", "gear", "bidirectional", "many"),
    ],
    rpm: 0,
  },
  gear24: {
    name: "24T Spur Gear",
    cat: "motion",
    icon: "⚙",
    mass: 14,
    color: 0xd4b46c,
    desc: "Balanced transmission gear",
    teeth: 24,
    radius: 0.82,
    ports: [
      port("AXLE", "mechanical", "rotary-coupling", "bidirectional", "one"),
      port("MESH", "mesh", "gear", "bidirectional", "many"),
    ],
    rpm: 0,
  },
  motor: {
    name: "Powered Motor",
    cat: "motion",
    icon: "◉",
    mass: 32,
    color: 0xd7793e,
    desc: "Electric rotary actuator",
    size: [0.9, 0.9, 1.1],
    ports: [
      port(
        "MOUNT",
        "mechanical",
        "structural-surface",
        "bidirectional",
        "many",
      ),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
      port(
        "SHAFT",
        "mechanical",
        "rotary-actuator-output",
        "bidirectional",
        "one",
      ),
    ],
    rpm: 120,
    power: 4,
    direction: 1,
    electricalEfficiency: 0.92,
    controlContract: "rotary-drive-v1",
    electricalContract: {
      kind: "configured-kilowatts-v1",
      configField: "power",
      minimumW: 1,
      baselineW: 0,
    },
  },
  rotor: {
    name: "Fixed-Pitch Rotor",
    cat: "motion",
    icon: "✣",
    mass: 18,
    color: 0x4f8990,
    desc: "Shaft-driven fixed-pitch aerodynamic rotor",
    hubRadiusM: 0.16,
    hubThicknessM: 0.12,
    radiusM: 0.9,
    bladeCount: 2,
    bladeChordM: 0.12,
    fixedPitchDeg: 14,
    handedness: 1,
    profileId: "utility-fixed-pitch-v1",
    ratedRpm: 1_800,
    maximumRpm: 2_400,
    ports: [
      port("SHAFT", "mechanical", "rotary-coupling", "bidirectional", "one"),
    ],
    flight: {
      propulsion: {
        kind: "shaft-rotor-aerodynamics-v1",
        localAxis: [0, 0, 1],
      },
    },
  },
  hinge: {
    name: "Hinge Joint",
    cat: "motion",
    icon: "⌁",
    color: 0x6d9da4,
    desc: "Torque-limited articulated pivot",
    ports: [
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
      port("BASE", "mechanical", "fixed", "bidirectional", "one"),
      port(
        "ARM",
        "mechanical",
        "rotary-position-actuator-output",
        "bidirectional",
        "one",
      ),
    ],
    mechanism: mechanismComponentDefinition("hinge"),
    controlContract: "rotary-position-v1",
    electricalContract: {
      kind: "mechanism-actuator-v1",
      minimumW: 1,
      baselineW: 0,
    },
  },
  lever: {
    name: "Control Lever",
    cat: "motion",
    icon: "╱",
    mass: 7,
    color: 0xc5cfd0,
    desc: "Mechanical input arm",
    size: [0.25, 1.6, 0.25],
    ports: [
      port("PIVOT", "mechanical", "fixed", "bidirectional", "one"),
      port("LINK", "mechanical", "fixed", "bidirectional", "one"),
    ],
    angle: 35,
  },
  spring: {
    name: "Coil Spring",
    cat: "motion",
    icon: "≋",
    color: 0x63bfa3,
    desc: "Elastic force element",
    ports: [
      port("END_A", "mechanical", "fixed", "bidirectional", "one"),
      port("END_B", "mechanical", "fixed", "bidirectional", "one"),
    ],
    mechanism: mechanismComponentDefinition("spring"),
  },
  rope: {
    name: "Rope",
    cat: "motion",
    icon: "⌇",
    color: 0xc79a62,
    desc: "Distributed flexible line that carries tension, not compression",
    ports: [
      port(
        "END_A",
        "mechanical",
        "flexible-termination",
        "bidirectional",
        "one",
      ),
      port(
        "END_B",
        "mechanical",
        "flexible-termination",
        "bidirectional",
        "one",
      ),
    ],
    flexibleLine: {
      kind: "flexible-line-v1",
      endpointPortA: "END_A",
      endpointPortB: "END_B",
      initialAxisPart: [0, -1, 0],
      maximumElementCount: 64,
    },
    lengthM: 4,
    diameterM: 0.04,
    linearDensityKgPerM: 0.895,
    axialStiffnessNPerM: 120_000,
    axialDampingNsPerM: 90,
    ultimateTensionN: 37_400,
    targetElementLengthM: 0.25,
    materialKey: "nylon-rope",
  },
  damper: {
    name: "Axial Damper",
    cat: "motion",
    icon: "⇵",
    color: 0x668aa0,
    desc: "Velocity-dependent axial force element",
    ports: [
      port("END_A", "mechanical", "fixed", "bidirectional", "one"),
      port("END_B", "mechanical", "fixed", "bidirectional", "one"),
    ],
    mechanism: mechanismComponentDefinition("damper"),
  },
  "release-coupler": {
    name: "Release Coupler",
    cat: "motion",
    icon: "⏏",
    color: 0xd89a42,
    desc: "Powered two-flange structural latch",
    ports: [
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
      port("FLANGE_A", "mechanical", "fixed", "bidirectional", "one"),
      port("FLANGE_B", "mechanical", "fixed", "bidirectional", "one"),
    ],
    mechanism: mechanismComponentDefinition("release-coupler"),
    controlContract: "release-coupler-v1",
    electricalContract: {
      kind: "release-actuator-v1",
      minimumW: 1,
      baselineW: 0,
    },
  },
  "linear-guide": {
    name: "Linear Guide",
    cat: "motion",
    icon: "↕",
    color: 0x7c8f9b,
    desc: "Constrains relative motion to one authored axis",
    ports: [
      port("BASE", "mechanical", "fixed", "bidirectional", "one"),
      port(
        "SLIDER",
        "mechanical",
        "linear-guide-output",
        "bidirectional",
        "one",
      ),
    ],
    mechanism: mechanismComponentDefinition("linear-guide"),
  },
  "linear-actuator": {
    name: "Linear Actuator",
    cat: "motion",
    icon: "⇅",
    color: 0xb68057,
    desc: "Power-limited force along an authored coordinate",
    ports: [
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
      port("BASE", "mechanical", "fixed", "bidirectional", "one"),
      port(
        "ROD",
        "mechanical",
        "linear-position-actuator-output",
        "bidirectional",
        "one",
      ),
    ],
    mechanism: mechanismComponentDefinition("linear-actuator"),
    controlContract: "linear-position-v1",
    electricalContract: {
      kind: "mechanism-actuator-v1",
      minimumW: 1,
      baselineW: 0,
    },
  },
  wheel: {
    name: "Grip Wheel",
    cat: "motion",
    icon: "⬤",
    color: 0x273237,
    desc: "Rounded rolling contact; suspension is built from mechanisms",
    ports: [
      port("AXLE", "mechanical", "rotary-coupling", "bidirectional", "one"),
      port(
        "SURFACE",
        "mechanical",
        "structural-surface",
        "bidirectional",
        "many",
      ),
      port("AIR", "resource", "compressible-gas", "bidirectional", "many", {
        mediumId: "dry-air-v1",
      }),
    ],
    mechanism: mechanismComponentDefinition("wheel"),
  },
  aircompressor: {
    name: "Electric Air Compressor",
    cat: "smart",
    icon: "◉",
    mass: 11,
    color: 0x6593a6,
    desc: "Powered dry-air source for pneumatic circuits",
    size: [0.7, 0.55, 0.8],
    powerWatts: 900,
    maximumGaugePressurePa: 520_000,
    maximumMassFlowKgS: 0.012,
    electricalEfficiency: 0.82,
    responseTimeS: 0.18,
    reliefAbsolutePressurePa: 610_000,
    motorThermalMassJPerK: 14_000,
    motorCoolingWPerK: 24,
    maximumMotorTemperatureK: 405,
    pressureRatioFlowMap: [
      [1, 1],
      [2, 0.82],
      [4, 0.48],
      [6, 0],
    ],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
      port("AIR", "resource", "compressible-gas", "source", "one", {
        mediumId: "dry-air-v1",
      }),
    ],
    pneumatic: {
      kind: "ambient-air-compressor-v1",
      outletPortId: "AIR",
      maximumGaugePressureField: "maximumGaugePressurePa",
      maximumMassFlowField: "maximumMassFlowKgS",
      electricalPowerField: "powerWatts",
      electricalEfficiencyField: "electricalEfficiency",
      responseTimeField: "responseTimeS",
      reliefAbsolutePressureField: "reliefAbsolutePressurePa",
      motorThermalMassField: "motorThermalMassJPerK",
      motorCoolingField: "motorCoolingWPerK",
      maximumMotorTemperatureField: "maximumMotorTemperatureK",
      pressureRatioFlowMapField: "pressureRatioFlowMap",
    },
    controlContract: "air-compressor-v1",
    electricalContract: {
      kind: "configured-watts-v1",
      configField: "powerWatts",
      minimumW: 50,
      baselineW: 0,
    },
  },
  airreservoir: {
    name: "Precharged Air Reservoir",
    cat: "smart",
    icon: "◒",
    mass: 16,
    color: 0x527d91,
    desc: "Rated dry-air control volume for pneumatic storage",
    size: [0.75, 0.75, 1.1],
    gasVolumeSizeM: [0.4, 0.4, 0.5],
    referenceInternalVolumeM3: 0.08,
    initialColdGaugePressurePa: 600_000,
    initialGasTemperatureK: 293.15,
    gasToShellConductanceWPerK: 10,
    maximumAbsolutePressurePa: 1_100_000,
    burstAbsolutePressurePa: 1_350_000,
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("AIR", "resource", "compressible-gas", "bidirectional", "many", {
        mediumId: "dry-air-v1",
      }),
    ],
    pneumatic: {
      kind: "ideal-gas-control-volume-v1",
      portId: "AIR",
      volumeField: "referenceInternalVolumeM3",
      initialGaugePressureField: "initialColdGaugePressurePa",
      initialTemperatureField: "initialGasTemperatureK",
      gasToShellConductanceField: "gasToShellConductanceWPerK",
      maximumAbsolutePressureField: "maximumAbsolutePressurePa",
      burstAbsolutePressureField: "burstAbsolutePressurePa",
      massModel: {
        kind: "box-gas-volume-v1",
        centerPartM: [0, 0, 0],
        sizeField: "gasVolumeSizeM",
      },
    },
  },
  pneumaticvalve: {
    name: "Three-Way Pneumatic Valve",
    cat: "smart",
    icon: "⇄",
    mass: 2.5,
    color: 0x78a9b5,
    desc: "Commands tire air to supply, hold, or atmosphere",
    size: [0.48, 0.42, 0.62],
    powerWatts: 18,
    orificeAreaM2: 0.000018,
    dischargeCoefficient: 0.72,
    openingTimeS: 0.12,
    commandDeadband: 0.04,
    leakageAreaM2: 2e-10,
    failPosition: 0,
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
      port("SUPPLY", "resource", "compressible-gas", "bidirectional", "one", {
        mediumId: "dry-air-v1",
      }),
      port("TIRE", "resource", "compressible-gas", "bidirectional", "many", {
        mediumId: "dry-air-v1",
      }),
    ],
    pneumatic: {
      kind: "three-way-valve-v1",
      supplyPortId: "SUPPLY",
      tirePortId: "TIRE",
      orificeAreaField: "orificeAreaM2",
      dischargeCoefficientField: "dischargeCoefficient",
      electricalPowerField: "powerWatts",
      openingTimeField: "openingTimeS",
      deadbandField: "commandDeadband",
      leakageAreaField: "leakageAreaM2",
      failPositionField: "failPosition",
    },
    controlContract: "three-way-pneumatic-valve-v1",
    electricalContract: {
      kind: "configured-watts-v1",
      configField: "powerWatts",
      minimumW: 3,
      baselineW: 0,
    },
  },
  computer: {
    name: "Logic Controller",
    cat: "smart",
    icon: "▦",
    mass: 8,
    color: 0x54cbb2,
    desc: "Programmable signal processor",
    size: [0.8, 0.32, 0.9],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("IN A", "signal", "signal-network", "sink", "many"),
      port("IN B", "signal", "signal-network", "sink", "many"),
      port("OUT", "signal", "signal-network", "source", "many"),
    ],
    channel: "A",
    electricalEfficiency: 0.92,
    controlContract: "controller-target-v1",
    electricalContract: {
      kind: "fixed-load-v1",
      requestW: 18,
      minimumW: 5,
      baselineW: 8,
    },
  },
  receiver: {
    name: "Command Receiver",
    cat: "smart",
    icon: "⌁",
    mass: 2.5,
    color: 0x6fb7c8,
    desc: "Powered remote or routed command input for Logic Controllers",
    size: [0.5, 0.22, 0.5],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    channel: "command",
    readings: ["command"],
    electricalEfficiency: 0.92,
    controlContract: "command-sink-v1",
    electricalContract: {
      kind: "fixed-load-v1",
      requestW: 2,
      minimumW: 0.5,
      baselineW: 1,
    },
  },
  navsensor: {
    name: "Navigation Sensor",
    cat: "smart",
    icon: "⌖",
    mass: 3.5,
    color: 0x78b9df,
    desc: "GNSS position, velocity, and local wind solution",
    size: [0.55, 0.2, 0.55],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    readings: [
      "altitude",
      "speed",
      "position_x",
      "position_z",
      "velocity_x",
      "velocity_z",
      "wind_x",
      "wind_z",
    ],
    electricalEfficiency: 0.92,
    electricalContract: {
      kind: "fixed-load-v1",
      requestW: 4,
      minimumW: 1,
      baselineW: 2,
    },
  },
  rangesensor: {
    name: "Conical Rangefinder",
    cat: "smart",
    icon: "◁",
    mass: 2.8,
    color: 0x8bc7f0,
    desc: "Powered finite-range beam with configurable field of view",
    size: [0.42, 0.52, 0.42],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    readings: [
      "proximity_detected",
      "proximity_range_m",
      "proximity_range_rate_mps",
      "proximity_relative_velocity_x",
      "proximity_relative_velocity_y",
      "proximity_relative_velocity_z",
    ],
    sensingAxis: [0, 1, 0],
    emitterOffsetM: [0, 0.27, 0],
    fieldOfViewDeg: 12,
    maximumRangeM: 150000,
    rangeResolutionM: 0.25,
    sensorContract: { kind: "conical-range-v1" },
    electricalEfficiency: 0.92,
    electricalContract: {
      kind: "fixed-load-v1",
      requestW: 8,
      minimumW: 3,
      baselineW: 5,
    },
  },
  sensor: {
    name: "Rotation Sensor",
    cat: "smart",
    icon: "◌",
    mass: 3,
    color: 0x75a9e8,
    desc: "Reads shaft speed",
    size: [0.45, 0.45, 0.28],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("SHAFT", "mechanical", "rotary-measurement", "sink", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    channel: "A",
    readings: ["rotation_rpm"],
  },
  imu: {
    name: "6-Axis IMU",
    cat: "smart",
    icon: "⌖",
    mass: 2,
    color: 0x6fb9e8,
    desc: "Measures attitude and acceleration",
    size: [0.5, 0.18, 0.5],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    channel: "IMU",
    readings: [
      "imu_roll_deg",
      "imu_pitch_deg",
      "imu_yaw_deg",
      "imu_rate_x",
      "imu_rate_y",
      "imu_rate_z",
      "imu_accel_x",
      "imu_accel_y",
      "imu_accel_z",
    ],
    electricalEfficiency: 0.92,
    electricalContract: {
      kind: "fixed-load-v1",
      requestW: 3,
      minimumW: 1,
      baselineW: 2,
    },
  },
  contactsensor: {
    name: "Contact Switch",
    cat: "smart",
    icon: "⊥",
    mass: 1.5,
    color: 0x70c9a9,
    desc: "Measures normal-contact state, part-frame normal wrench, world-frame resultant point contact, friction, and water contact",
    size: [0.48, 0.16, 0.48],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    readings: [
      "contact",
      "contact_force_n",
      "contact_normal_force_part_x_n",
      "contact_normal_force_part_y_n",
      "contact_normal_force_part_z_n",
      "contact_normal_moment_part_x_nm",
      "contact_normal_moment_part_y_nm",
      "contact_normal_moment_part_z_nm",
      "contact_min_friction_coefficient",
      "contact_resultant_point_world_x_m",
      "contact_resultant_point_world_y_m",
      "contact_resultant_point_world_z_m",
      "contact_resultant_normal_world_x",
      "contact_resultant_normal_world_y",
      "contact_resultant_normal_world_z",
      "contact_resultant_normal_force_n",
      "water_contact",
    ],
  },
  thermalprobe: {
    name: "Thermal Probe",
    cat: "smart",
    icon: "♨",
    mass: 1.2,
    color: 0xe18455,
    desc: "Measures temperature and heat flux",
    size: [0.28, 0.5, 0.28],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    readings: ["temperature_c", "heat_flux_kw_m2"],
  },
  pressureprobe: {
    name: "Air Data Probe",
    cat: "smart",
    icon: "◁",
    mass: 2,
    color: 0x72aee6,
    desc: "Measures static and dynamic air pressure",
    size: [0.3, 0.3, 0.65],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    readings: ["static_pressure_pa", "dynamic_pressure_pa", "air_density"],
  },
  tirepressureprobe: {
    name: "Tire Pressure Sensor",
    cat: "smart",
    icon: "◴",
    mass: 0.7,
    color: 0x6eb5ca,
    desc: "Reads an explicitly connected dry-air circuit",
    size: [0.3, 0.24, 0.36],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
      port("AIR", "resource", "compressible-gas", "bidirectional", "one", {
        mediumId: "dry-air-v1",
      }),
    ],
    readings: [
      "tire_pressure_absolute_pa",
      "tire_pressure_gauge_pa",
      "tire_gas_temperature_k",
    ],
    pneumatic: { kind: "pressure-sensor-v1", portId: "AIR" },
    electricalContract: {
      kind: "fixed-load-v1",
      requestW: 2,
      minimumW: 0.5,
      baselineW: 1,
    },
  },
  loadcell: {
    name: "Load Cell",
    cat: "smart",
    icon: "⋈",
    mass: 3,
    color: 0xd7b25d,
    desc: "Measures attachment load and capacity ratio",
    size: [0.55, 0.22, 0.55],
    ports: [
      port("A", "mechanical", "fixed", "bidirectional", "one"),
      port("B", "mechanical", "fixed", "bidirectional", "one"),
      port("SIGNAL", "signal", "signal-network", "source", "many"),
    ],
    readings: ["load_n", "load_ratio"],
  },
  gyro: {
    name: "Balance Gyro",
    cat: "smart",
    icon: "◎",
    mass: 12,
    color: 0x63c7af,
    desc: "Reaction-torque balance actuator",
    size: [0.65, 0.65, 0.3],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("CONTROL", "signal", "signal-network", "sink", "one"),
    ],
    power: 18,
    maxTorqueNm: 180,
    momentumCapacityNms: 90,
    electricalEfficiency: 0.92,
    controlContract: "reaction-wheel-v1",
    electricalContract: {
      kind: "configured-kilowatts-v1",
      configField: "power",
      minimumW: 5,
      baselineW: 0,
    },
  },
  battery: {
    name: "Power Cell",
    cat: "smart",
    icon: "▥",
    mass: 24,
    color: 0x79b86b,
    desc: "Stores electrical energy",
    size: [0.75, 1, 0.55],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "source", "many"),
    ],
    capacityWh: 100,
    maxOutputWatts: 50000,
    dischargeEfficiency: 0.96,
    electricalSource: {
      kind: "stored-energy-source-v1",
      capacityField: "capacityWh",
      maximumOutputField: "maxOutputWatts",
    },
  },
  propellanttank: {
    name: "Bladder Propellant Tank",
    cat: "smart",
    icon: "◫",
    mass: 68,
    color: 0x87979d,
    desc: "Finite monopropellant storage with an outlet-anchored bladder",
    size: [1.2, 2.4, 1.2],
    capacityKg: 900,
    initialUsableMassKg: 900,
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("OUTLET", "resource", "material-resource", "source", "many", {
        mediumId: "hydrogen-peroxide-90-v1",
      }),
    ],
    materialStore: {
      kind: "propellant-store-v1",
      mediumId: "hydrogen-peroxide-90-v1",
      outletPortId: "OUTLET",
      capacityField: "capacityKg",
      initialMassField: "initialUsableMassKg",
      storageSolid: {
        kind: "box-v1",
        sizeFraction: [0.82, 0.9, 0.82],
        centerFraction: [0, 0, 0],
      },
      storageAxisPart: [0, -1, 0],
      fillLaw: { kind: "positive-displacement-bladder-v1" },
    },
  },
  powerbus: {
    name: "Power Distribution Bus",
    cat: "smart",
    icon: "⇶",
    mass: 4,
    color: 0xd6a34a,
    desc: "Routes one power source to multiple downstream consumers",
    size: [0.72, 0.22, 0.52],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER IN", "power", "electrical-network", "sink", "one"),
      port("POWER OUT", "power", "electrical-network", "source", "many"),
    ],
  },
  headlight: {
    name: "Powered Headlamp",
    cat: "smart",
    icon: "◉",
    mass: 3,
    color: 0xd5d0b5,
    desc: "Placeable 1,600 lumen shadow-casting lamp",
    size: [0.42, 0.42, 0.34],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("POWER", "power", "electrical-network", "sink", "one"),
      port("SIGNAL", "signal", "signal-network", "sink", "one"),
    ],
    lumens: 1600,
    powerWatts: 55,
    electricalEfficiency: 0.92,
    actuator: {
      kind: "luminaire-v1",
      channel: "lights",
      electricalPowerW: 55,
      luminousFluxLm: 1600,
    },
    controlContract: "luminaire-v1",
    electricalContract: {
      kind: "configured-watts-v1",
      configField: "powerWatts",
      minimumW: 1,
      baselineW: 0,
    },
  },
  rocket: {
    name: "Vector Thruster",
    cat: "smart",
    icon: "▼",
    mass: 55,
    color: 0xe16c42,
    desc: "Throttleable rocket engine",
    size: [0.8, 1.15, 0.8],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("SIGNAL", "signal", "signal-network", "sink", "one"),
      port("PROPELLANT", "resource", "material-resource", "sink", "many", {
        mediumId: "hydrogen-peroxide-90-v1",
      }),
    ],
    maximumMassFlowKgS: 24,
    exitAreaM2: 0.06,
    throttleTimeConstantS: 0.18,
    minimumStableThrottle: 0.15,
    thermalLossFraction: 0.1,
    flight: {
      propulsion: {
        kind: "pressure-nozzle-v1",
        mediumId: "hydrogen-peroxide-90-v1",
        inletPortId: "PROPELLANT",
        maximumMassFlowField: "maximumMassFlowKgS",
        exitAreaField: "exitAreaM2",
        throttleTimeConstantField: "throttleTimeConstantS",
        minimumStableThrottleField: "minimumStableThrottle",
        thermalLossFractionField: "thermalLossFraction",
        localAxis: [0, 1, 0],
        gimbalRangeRad: 0.12,
        ratedCurve: [
          {
            flowFraction: 0.15,
            exitVelocityMps: 650,
            exitPressurePa: 120_000,
          },
          {
            flowFraction: 0.55,
            exitVelocityMps: 760,
            exitPressurePa: 142_000,
          },
          {
            flowFraction: 1,
            exitVelocityMps: 850,
            exitPressurePa: 161_325,
          },
        ],
      },
    },
    controlContract: "pressure-nozzle-v1",
  },
  rcs: {
    name: "Reaction Control Pod",
    cat: "smart",
    icon: "✣",
    mass: 12,
    color: 0x9aaeb2,
    desc: "Finite-force lateral attitude and translation thruster",
    size: [0.72, 0.42, 0.72],
    ports: [
      port("MOUNT", "mechanical", "fixed", "bidirectional", "one"),
      port("SIGNAL", "signal", "signal-network", "sink", "one"),
      port("PROPELLANT", "resource", "material-resource", "sink", "many", {
        mediumId: "hydrogen-peroxide-90-v1",
      }),
    ],
    maximumMassFlowKgS: 1.8,
    exitAreaM2: 0.0045,
    throttleTimeConstantS: 0.06,
    minimumStableThrottle: 0.15,
    thermalLossFraction: 0.1,
    flight: {
      propulsion: {
        kind: "pressure-nozzle-v1",
        mediumId: "hydrogen-peroxide-90-v1",
        inletPortId: "PROPELLANT",
        maximumMassFlowField: "maximumMassFlowKgS",
        exitAreaField: "exitAreaM2",
        throttleTimeConstantField: "throttleTimeConstantS",
        minimumStableThrottleField: "minimumStableThrottle",
        thermalLossFractionField: "thermalLossFraction",
        localAxis: [0, 1, 0],
        gimbalRangeRad: 0,
        ratedCurve: [
          {
            flowFraction: 0.15,
            exitVelocityMps: 650,
            exitPressurePa: 120_000,
          },
          {
            flowFraction: 0.55,
            exitVelocityMps: 760,
            exitPressurePa: 142_000,
          },
          {
            flowFraction: 1,
            exitVelocityMps: 850,
            exitPressurePa: 161_325,
          },
        ],
      },
    },
    controlContract: "pressure-nozzle-v1",
  },
};

for (const [type, definition] of Object.entries(TYPE_DEFINITIONS)) {
  const geometryContract = COMPONENT_GEOMETRY_DEFINITIONS[type];
  if (!geometryContract)
    throw new Error(`Missing canonical geometry contract for ${type}`);
  definition.geometryContract = geometryContract;
}

export const TYPES = issueInertPlainData(TYPE_DEFINITIONS);

export const FLIGHT_MATERIALS = {
  beam: { heatLimit: 660, specificHeat: 900, emissivity: 0.28, cd: 0.72 },
  plate: { heatLimit: 660, specificHeat: 900, emissivity: 0.28, cd: 0.82 },
  nosecone: { heatLimit: 1450, specificHeat: 780, emissivity: 0.82, cd: 0.16 },
  heatshield: {
    heatLimit: 2800,
    specificHeat: 1250,
    emissivity: 0.9,
    cd: 0.42,
    ablative: true,
    pyrolysisTemperatureK: 560,
    heatOfAblationJkg: 22000000,
  },
  fin: { heatLimit: 820, specificHeat: 880, emissivity: 0.72, cd: 0.14 },
  battery: { heatLimit: 105, specificHeat: 1050, emissivity: 0.78, cd: 0.86 },
  headlight: { heatLimit: 155, specificHeat: 720, emissivity: 0.76, cd: 0.78 },
  computer: { heatLimit: 125, specificHeat: 920, emissivity: 0.82, cd: 0.86 },
  receiver: { heatLimit: 125, specificHeat: 900, emissivity: 0.8, cd: 0.84 },
  navsensor: { heatLimit: 125, specificHeat: 900, emissivity: 0.8, cd: 0.84 },
  rangesensor: {
    heatLimit: 125,
    specificHeat: 880,
    emissivity: 0.8,
    cd: 0.78,
  },
  rocket: { heatLimit: 980, specificHeat: 620, emissivity: 0.76, cd: 0.58 },
  rcs: { heatLimit: 720, specificHeat: 760, emissivity: 0.7, cd: 0.74 },
  propellanttank: {
    heatLimit: 420,
    specificHeat: 880,
    emissivity: 0.66,
    cd: 0.62,
  },
  default: { heatLimit: 520, specificHeat: 700, emissivity: 0.65, cd: 0.82 },
};
