export const POWER_REASON_CODES = Object.freeze([
  'INVALID_POWER_CONFIGURATION',
  'UNSUPPORTED_POWER_TOPOLOGY',
  'UNSUPPORTED_SIGNAL_TOPOLOGY',
  'INVALID_POWER_CHECKPOINT',
  'POWER_STEP_PENDING',
  'INVALID_POWER_STEP',
  'INVALID_SIGNAL_COMMAND',
  'INVALID_MOTOR_SAMPLE',
  'INVALID_MOTOR_INERTIA',
  'ENERGY_INVARIANT',
]);
export const CONTROLLER_REASON_CODES = Object.freeze([
  'INVALID_CONTROLLER_CONFIGURATION',
  'INVALID_CONTROLLER_PROGRAM',
  'INVALID_CONTROLLER_SNAPSHOT',
  'INVALID_CONTROLLER_OUTPUT',
]);
