export const DT = 1 / 120;
export const PHASES = Object.freeze([
  'sensor-snapshot',
  'controller-commands',
  'power-signals',
  'actuators-constraints',
  'environment-forces',
  'integration-contacts',
  'structure-failure',
  'thermal-ablation',
  'telemetry',
]);
export const REASON_CODES = Object.freeze([
  'OK',
  'INVALID_CONFIGURATION',
  'ENERGY_INVARIANT',
  'INVALID_COMMAND',
  'INVALID_BODY',
  'INVALID_VECTOR',
  'INVALID_CHECKPOINT',
  'SESSION_FAILED',
  'SESSION_DISPOSED',
  'REPLACEMENT_PENDING',
  'NON_FINITE_STATE',
  'INPUT_LIMIT',
  'INVARIANT_VIOLATION',
  'PHYSICS_FAILURE',
  'GEAR_MOTION_LIMIT',
  'ROPE_MOTION_LIMIT',
  'CORD_MOTION_LIMIT',
  'INVALID_PREDICATE',
  'INVALID_TICK_COUNT',
  'INVALID_ELAPSED_TIME',
]);
export function deterministicProjection(frame) {
  return {
    tick: frame.tick,
    physics: frame.physics,
    ...(frame.springs ? { springs: frame.springs } : {}),
    ...(frame.ropes ? { ropes: frame.ropes } : {}),
    ...(frame.gears ? { gears: frame.gears } : {}),
    ...(frame.contacts ? { contacts: frame.contacts } : {}),
    energy: frame.energy,
    power: frame.power,
    sensors: frame.sensors,
    receiverControl: frame.receiverControl,
    ...(frame.cameras ? { cameras: frame.cameras } : {}),
    status: frame.status,
  };
}
