import { ROPE_SCHEMA } from '../src/model/rope.mjs';
import { CONTROLLER_AUTHORING_SCHEMA } from '../src/model/controller-authoring.mjs';
import { LEARNING_MODEL_SCHEMA } from '../src/model/learning-model.mjs';
import { CATALOG, MATERIALS } from '../src/model/catalog.mjs';
import { CONTROL_BINDING_SCHEMA } from '../src/model/control-bindings.mjs';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
const schemaURL = new URL('../src/model/blueprint.schema.json', import.meta.url);
const targetURL = new URL('../src/model/generated/blueprint-validator.mjs', import.meta.url);
export function buildBlueprintSchema() {
  const schema = JSON.parse(readFileSync(schemaURL, 'utf8'));
  const part = schema.$defs.part;
  const edge = schema.$defs.connection;
  schema.$defs.connection = {
    oneOf: [
      {
        ...edge,
        properties: {
          ...edge.properties,
          kind: { enum: edge.properties.kind.enum.filter((k) => k !== 'rope') },
          rope: false,
        },
      },
      {
        ...edge,
        required: [...edge.required, 'rope'],
        properties: {
          ...edge.properties,
          kind: { const: 'rope' },
          rope: structuredClone(ROPE_SCHEMA),
        },
      },
    ],
  };
  part.properties.type = { type: 'string', enum: Object.keys(CATALOG) };
  part.properties.controlBinding = structuredClone(CONTROL_BINDING_SCHEMA);
  part.properties.controllerProgram = structuredClone(CONTROLLER_AUTHORING_SCHEMA);
  part.properties.jointBinding = { $ref: '#/$defs/id' };
  part.properties.springBinding = { $ref: '#/$defs/id' };
  part.properties.targetBinding = { $ref: '#/$defs/id' };
  part.properties.learningModel = structuredClone(LEARNING_MODEL_SCHEMA);
  part.properties.authoredMaterial.properties.body = {
    type: 'string',
    enum: Object.keys(MATERIALS),
  };
  part.allOf = Object.entries(CATALOG).map(([type, definition]) => ({
    if: { required: ['type'], properties: { type: { const: type } } },
    then: {
      properties: {
        controlBinding:
          type === 'commandReceiver' ? structuredClone(CONTROL_BINDING_SCHEMA) : false,
        controllerProgram:
          type === 'logicController' ? structuredClone(CONTROLLER_AUTHORING_SCHEMA) : false,
        jointBinding: type === 'jointAngleSensor' ? { $ref: '#/$defs/id' } : false,
        springBinding: type === 'travelSensor' ? { $ref: '#/$defs/id' } : false,
        targetBinding: type === 'targetSensor' ? { $ref: '#/$defs/id' } : false,
        learningModel:
          type === 'learningController' ? structuredClone(LEARNING_MODEL_SCHEMA) : false,
        parameters: {
          type: 'object',
          additionalProperties: false,
          required: Object.entries(definition.parameterDefinitions)
            .filter(([, value]) => !value.optional)
            .map(([key]) => key),
          properties: Object.fromEntries(
            Object.entries(definition.parameterDefinitions).map(([key, value]) => [
              key,
              {
                type: value.type,
                minimum: value.minimum,
                maximum: value.maximum,
                ...(value.enum ? { enum: [...value.enum] } : {}),
              },
            ]),
          ),
        },
      },
    },
  }));
  return schema;
}
export function generateSchema({ check = false } = {}) {
  const schema = buildBlueprintSchema();
  const compiler = new Ajv2020({
    strict: true,
    allErrors: false,
    code: { source: true, esm: true, lines: true },
  });
  compiler.compile(schema);
  const output =
    '// Generated by scripts/generate-schema.mjs; edit blueprint.schema.json and catalog.mjs.\n' +
    standaloneCode(compiler, { validateBlueprint: schema.$id }) +
    '\nexport {validateBlueprint as default};\n';
  // Model validators must be self-contained. Helpers imported from an external
  // runtime would break the model boundary even though generation is build-time.
  if (/\brequire\s*\(|\bimport\s/.test(output))
    throw Error('generated validator imports runtime code');
  if (check) {
    if (readFileSync(targetURL, 'utf8') !== output)
      throw Error('blueprint validator is stale; run node scripts/generate-schema.mjs');
  } else writeFileSync(targetURL, output);
  return { ok: true };
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    generateSchema({ check: process.argv.includes('--check') });
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
